# Configuracao do Driver e URL de Conexao
quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url= jdbc:mysql://localhost:3306/acaba_aqui

# Credenciais de acesso
quarkus.datasource.username={username}
quarkus.datasource.password={password}

#Estrategia Hibernate
quarkus.hibernate-orm.database.generation=update
quarkus.log.level=INFO
